.azure/pipelines/azure-pipelines-deploy.yml
infrastructure/app-manage.tf
infrastructure/app-portal.tf

To disable continuous deployment, deploy pipeline is updated with v3.18.2 for application deploy pipeline 
with tag 1.31 of node app service modules, DOCKER_ENABLE_CI is set to false

fix(tooling): updating common pipeline tag and node app module version 

---

.azure/pipelines/azure-pipelines-pr.yml
package-lock.json
packages/lib/middleware/errors.js
packages/lib/middleware/errors.test.js
packages/lib/package.json

Change to the shared default error handler to check for Prisma errors. Prisma errors are logged, but not shown directly to users. Instead new and simplified error messages are returned, with a Prisma code is present.
This is only a fallback.
N/A

feat: wrap prisma errors so they aren't shown to users

---

.azure/pipelines/azure-pipelines-build.yml
.azure/pipelines/azure-pipelines-deploy.yml

We are moving to using git commit hashes for Docker image tagging and deployments. This should help deployments be more robust, see the [documentation](https://pins-ds.atlassian.net/wiki/spaces/CS/pages/1719861253/App+Service+Deployments)
https://pins-ds.atlassian.net/browse/DEV-337

ci: use git commit hash for deployments

---

packages/dynamic-forms/src/lib/session-answer-store.js
packages/dynamic-forms/src/lib/session-answer-store.test.js

This is to avoid bugs related to changing answers to yes/no from boolean values, this should apply to the journey response answers, but not to the session data.
Previously the answers object was a reference to the session answers object, so the session was unintentionally edited.
The symptom of this was when answering "Has agent" question with yes, the agent questions were not displayed as the answer value was "true" instead of "yes".

fix(dynamic-forms): use a copy of session data for journey response

---

apps/manage/src/app/views/cases/view/journey.js
apps/manage/src/app/views/cases/view/questions.js
apps/manage/src/app/views/cases/view/types.d.ts
apps/manage/src/app/views/cases/view/view-model.js
apps/manage/src/app/views/cases/view/view-model.test.js
packages/dynamic-forms/src/components/date-period/index.njk
packages/dynamic-forms/src/components/date-period/question.js
packages/dynamic-forms/src/components/date-period/question.test.js
packages/dynamic-forms/src/components/date/question.test.js
packages/dynamic-forms/src/index.js
packages/dynamic-forms/src/questions/questions.js
packages/dynamic-forms/src/validator/date-period-validator.js
packages/dynamic-forms/src/validator/date-period-validator.test.js

Use a new date period component for the reps period, so both dates can be edited on one page.
Relates to: https://pins-ds.atlassian.net/browse/CROWN-6

feat(manage): use date-period component for representations period

---

apps/manage/src/app/views/cases/create-a-case/question-utils.js

allow both ' and ’ type apostrophes in names
https://pins-ds.atlassian.net.mcas.ms/browse/CROWN-36
https://pins-ds.atlassian.net.mcas.ms/browse/CROWN-51

fix(manage): allow both ' and ’ type apostrophes in names

---

packages/dynamic-forms/src/validator/validator.js
packages/dynamic-forms/src/validator/validator.test.js

Validator now trims input prior to validation, this assures that no inputs will fail validation because of whitespace. Additionally, this avoid whitespaces in submissions to database.
https://pins-ds.atlassian.net/browse/CROWN-128

fix(manage): trim user inputs to avoid issues with whitespaces

---

apps/portal/src/app/views/applications/view/have-your-say/success.njk

Info and Relationships - Semantic Markup Not Used Appropriately
- override pageHeading block so that empty h1 tag is omitted
https://pins-ds.atlassian.net/browse/CROWN-386

fix(portal): override pageHeading block so that empty h1 tag is omitted

---

packages/dynamic-forms/package.json
packages/dynamic-forms/src/components/address/question.js
packages/dynamic-forms/src/components/date-period/question.js
packages/dynamic-forms/src/components/date/question.js
packages/dynamic-forms/src/components/identifier/question.js
packages/dynamic-forms/src/components/multi-field-input/question.js
packages/dynamic-forms/src/components/number-entry/question.js
packages/dynamic-forms/src/components/single-line-input/question.js
packages/dynamic-forms/src/components/text-entry-redact/question.js
packages/dynamic-forms/src/components/text-entry/question.js
packages/dynamic-forms/src/components/unit-option-entry/question.js
packages/dynamic-forms/src/questions/options-question.js
packages/dynamic-forms/src/questions/question-types.d.ts
packages/dynamic-forms/src/questions/question.js
packages/lib/forms/custom-components/representation-comment/question.js

- [refactor(dynamic-forms): add common question parameters into a type](https://github.com/Planning-Inspectorate/crown-developments/commit/3d222efbc60e046635675a2fff0ca2dfd1bb7929)
To avoid the need to add props to each question definition when it applies to the root Question class.
N/A

refactor(dynamic-forms): add common question parameters into a type

---

infrastructure/.terraform.lock.hcl
infrastructure/providers.tf

Updating AzureRM to latest version 4.26.0 as part of monthly infrastructure updates 
terraform latest version is 1.11.3 which is included with in the required condition [">= 1.1.6, < 1.12.0"]

chore(tooling): updating latest AzureRM version

---

apps/manage/src/app/config.js
apps/portal/src/app/config.js

Start-up required a test id template for notify which now fails on prod as there is no template and we have turned gov notify on

fix(app): remove unnecessary template id

---

apps/portal/src/app/views/applications/view/have-your-say/index.js
packages/lib/forms/custom-components/representation-attachments/index.njk
packages/lib/forms/custom-components/representation-attachments/upload-documents.js
packages/lib/forms/custom-components/representation-attachments/upload-documents.test.js

Severity: Minor; Inline error message missing from upload page
Severity: Minor: Inline messages should appear above the control
Severity: Minor: Error message summary does not refresh
Severity: Minor: Upload page cannot upload 4 files or more
https://pins-ds.atlassian.net/browse/CROWN-848
https://pins-ds.atlassian.net/browse/CROWN-854
https://pins-ds.atlassian.net/browse/CROWN-850
https://pins-ds.atlassian.net/browse/CROWN-855

fix(app): add inline error to doc upload form

---

apps/manage/src/app/views/cases/create-a-case/questions.js
apps/manage/src/app/views/cases/list/controller.js
apps/manage/src/app/views/cases/list/controller.test.js
apps/manage/src/app/views/cases/view/notification.js
apps/manage/src/app/views/cases/view/notification.test.js
apps/manage/src/app/views/cases/view/questions.js
apps/manage/src/app/views/cases/view/update-case.test.js
apps/portal/src/app/views/applications/view/view-model.js
packages/dynamic-forms/src/validator/coordinates-validator.test.js

Changes to the site location coordinates so Easting appears before Northing when creating a new case, editing a new case and overview 
https://pins-ds.atlassian.net/jira/software/projects/CROWN/boards/267?selectedIssue=CROWN-630

fix(manage): switched coordinates so easting appears before northing

---

packages/dynamic-forms/src/components/address/index.njk
packages/dynamic-forms/src/components/address/question.test.js
packages/lib/forms/representations/question-utils.js

the hint for page add-representation/myself then option post selected has been added under the h1 title "We will not publish your address"
438 https://pins-ds.atlassian.net/browse/CROWN-438

fix(manage): hint now displaying under what is your address

---

apps/manage/src/app/views/cases/view/question-utils.js
apps/manage/src/app/views/cases/view/question-utils.test.js
apps/manage/src/app/views/cases/view/types.d.ts
apps/manage/src/app/views/cases/view/view-model.js
apps/manage/src/app/views/cases/view/view-model.test.js
packages/database/src/migrations/20250731143131_add_event_prep_sitting_reporting_durations/migration.sql
packages/database/src/migrations/20250731143309_remove_event_duration/migration.sql
packages/database/src/schema.prisma
packages/lib/util/numbers.js
packages/lib/util/numbers.test.js

update to hearing and inquiry durations from radio button to labels which accept numerical answers for prep, sitting and reporting fields and display under duration under manage case
hearing ticket - https://pins-ds.atlassian.net/browse/CROWN-500
inquiry ticket - https://pins-ds.atlassian.net/browse/CROWN-776

feat(manage): add duration fields for hearing and inquiry prep sitting and reporting

---

apps/portal/src/app/views/applications/view/have-your-say/declaration.njk

Severity: Minor - declaration page uses inconsistent font size and weight
override pageHeading so that we can use govuk-heading-l instead of xl
https://pins-ds.atlassian.net/browse/CROWN-959

fix(portal): Severity: Minor - declaration page uses inconsistent font size and weight

---

apps/portal/src/app/views/applications/view/view-model.js
apps/portal/src/app/views/applications/view/written-representations/controller.test.js
packages/lib/util/questions.js
packages/lib/util/questions.test.js

[PORTAL] Prevent read more link from being presented when comment is not longer than 500 chars
https://pins-ds.atlassian.net/browse/CROWN-239

fix(portal): prevent read more link from always being presented

---

apps/manage/src/app/views/cases/list/controller.test.js
packages/lib/util/search-queries.js
packages/lib/util/search-queries.test.js

Fixed the way the whereClause builder creates queries when there are multiple queries. The original way doesn't work with MSSQL

fix(package): fix multiple queries not supported by search

---

apps/manage/src/app/views/cases/view/manage-reps/review/controller.js
apps/manage/src/app/views/cases/view/manage-reps/review/controller.test.js
package-lock.json
package.json

this ensures newline handling is consistent across the front and back end, so that string index offsets match between the comment, redacted comment, and redaction suggestions
https://pins-ds.atlassian.net/browse/CROWN-1102
may also fix https://pins-ds.atlassian.net/browse/CROWN-1100

fix(manage): update dynamic-forms for redaction fixes and normalise new lines

---

apps/manage/src/app/sass/style.scss
apps/manage/src/app/views/cases/view/manage-reps/review/redact-confirmation.njk
apps/manage/src/app/views/cases/view/manage-reps/review/review-comment.njk
apps/portal/src/app/sass/style.scss
apps/portal/src/app/views/applications/view/application-info/view.njk
apps/portal/src/app/views/applications/view/written-representations/read-more/view.njk
apps/portal/src/app/views/applications/view/written-representations/representation.njk

Added the pins-pre-wrap class to redact-confirmation and review-comment.njk to add line breaks when present in the comment for readability on both Portal and Manage app.
https://pins-ds.atlassian.net/browse/CROWN-1097

fix(app): add line breaks to representations for improved readability

---

apps/manage/src/app/views/cases/view/view-model.js
apps/manage/src/app/views/cases/view/view-model.test.js

Fixes bug introduced in [this branch](https://github.com/Planning-Inspectorate/crown-developments/commit/9a1485366bdef00a05709324e212c11b71cfd852) where changing the procedure when an event doesn't exist causes a Prisma error
https://pins-ds.atlassian.net/browse/CROWN-152

fix(manage): fix an issue where you can't update procedure if an event doesn't exist
