- .azure/pipelines/azure-pipelines-build.yml
- .azure/pipelines/azure-pipelines-deploy.yml
- apps/portal/Dockerfile
> fix build pipeline

- .azure/pipelines/azure-pipelines-deploy.yml
> ci: correct node_script reference

- .azure/pipelines/azure-pipelines-variables.yml
- infrastructure/.pre-commit-config.yaml
- infrastructure/.tflint.hcl
- infrastructure/data.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/locals.tf
- infrastructure/main.tf
- infrastructure/networking.tf
- infrastructure/pipelines/terraform-ci-commit.yaml
- infrastructure/regions.tf
- infrastructure/secondary-networking.tf
- infrastructure/terraform.tfvars
- infrastructure/variables.tf
> feat(tooling): creating networking and resources

- .azure/pipelines/azure-pipelines-db-seed.yml
- .azure/pipelines/azure-pipelines-deploy.yml
> fix(ci): use the crown key vault for secrets

- infrastructure/app-manage.tf
- infrastructure/database-monitoring.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/front-door-manage.tf
- infrastructure/front-door-portal.tf
- infrastructure/locals.tf
- Creating sql config for each env
- groups have been created in azure portal
> feat: sql config .tfvars

- .azure/pipelines/azure-pipelines-build.yml
- .azure/pipelines/azure-pipelines-db-seed.yml
- .azure/pipelines/azure-pipelines-deploy.yml
> fix(ci): correct naming to match scripts and infra

- apps/manage/Dockerfile
- apps/portal/Dockerfile
> fix(apps): generate db client in docker build

- .azure/pipelines/azure-pipelines-deploy.yml
> fix(ci): correct naming to match container repository

- apps/manage/src/app/config-types.d.ts
- apps/manage/src/app/config.js
- apps/manage/src/util/redis.js
- apps/portal/Dockerfile
- apps/portal/src/app/config-types.d.ts
- apps/portal/src/app/config.js
- apps/portal/src/util/redis.js
- infrastructure/app-manage.tf
- infrastructure/app-portal.tf
- infrastructure/locals.tf
- packages/lib/util/redis.js
> configure sessions & redis cache

- infrastructure/locals.tf
> fix(infrastructure): missing )

- apps/manage/src/app/config.js
- apps/portal/src/app/config.js
> fix(apps): use PORT env var set by app service

- commitlint.config.js
- infrastructure/app-manage.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/locals.tf
- infrastructure/variables.tf
> feat: app settings for azure access

- infrastructure/app-manage.tf
- infrastructure/app-portal.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/variables.tf
> fix(infrastructure): align env var naming to apps

- infrastructure/environments/training.tfvars
> fix: correcting-client-id

- apps/manage/src/app/monitoring.js
- apps/portal/src/app/monitoring.js
- packages/lib/package.json
- packages/lib/util/async-handler.js
- packages/lib/util/async-handler.test.js
- ensure we catch async controller errors
- remove specific package versions from the lib package
> a few setup fixes

- apps/manage/src/app/router.js
> fix(manage): correct import for redis

- packages/sharepoint/src/utils/url-builder/url-builder.js
- packages/sharepoint/src/utils/url-builder/url-builder.test.js
> feat(utils): add url-builder to packages

- apps/manage/.env.example
> feat(manage): update env example file

- apps/manage/Dockerfile
- apps/portal/Dockerfile
https://github.com/prisma/prisma/issues/25817
> fix(docker): try alpine 3.20

- apps/manage/Dockerfile
- apps/portal/Dockerfile
- package-lock.json
- package.json
Fixes previous issue, see https://github.com/prisma/prisma/pull/25824
> chore: update prisma and use latest alpine image

- infrastructure/app-manage.tf
- infrastructure/app-portal.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/locals.tf
- infrastructure/variables.tf
> feat(infrastructure): adding Microsoft Authentication to non-prod environments

- .azure/pipelines/azure-pipelines-deploy.yml
> fix(ci): deploy manage image to correct app

- apps/manage/src/app/views/cases/create-a-case/journey.js
- apps/manage/src/app/views/cases/view/questions.js
- apps/manage/src/app/views/cases/view/view-model.js
- packages/dynamic-forms/src/components/address/question.test.js
- packages/dynamic-forms/src/components/boolean/question.test.js
- packages/dynamic-forms/src/components/date/question.test.js
- packages/dynamic-forms/src/components/multi-field-input/question.test.js
- packages/dynamic-forms/src/components/radio/question.test.js
- packages/dynamic-forms/src/components/select/question.test.js
- packages/dynamic-forms/src/components/utils/question-has-answer.js
- packages/dynamic-forms/src/components/utils/question-has-answer.test.js
- packages/dynamic-forms/src/journey/journey.js
- packages/dynamic-forms/src/journey/journey.test.js
- packages/dynamic-forms/src/questions/options-question.test.js
- packages/dynamic-forms/src/questions/question.js
- packages/dynamic-forms/src/questions/question.test.js
Fixes to the create a case and case details pages:
- show application type on case details page
- fix "has agent" -> "Yes" journey
- add back link to first create-a-case question
> fix(manage): create a case

- .husky/pre-commit
- apps/manage/src/app/views/cases/view/controller.js
- apps/manage/src/app/views/cases/view/controller.test.js
- apps/manage/src/app/views/cases/view/index.js
- apps/manage/src/app/views/cases/view/types.d.ts
- apps/manage/src/app/views/cases/view/view-model.js
- apps/manage/src/app/views/cases/view/view-model.test.js
- apps/manage/src/app/views/cases/view/view.njk
- apps/manage/src/app/views/layouts/main.njk
- packages/dynamic-forms/src/lib/address.d.ts
Ability to edit all case (and relation) fields (except Representations which will be managed separately).
https://pins-ds.atlassian.net/browse/CROWN-6
> feat(manage): edit case fields

- infrastructure/app-manage.tf
- infrastructure/locals.tf
Add sharepoint details to terraform
> feat(infra): add Sharepoint to terraform

- apps/manage/.env.example
- apps/manage/src/app/app.js
- apps/manage/src/app/auth/auth-service.js
- apps/manage/src/app/config-types.d.ts
- apps/manage/src/app/config.js
- apps/manage/src/app/router.js
- apps/manage/src/app/views/cases/create-a-case/index.js
- apps/manage/src/app/views/cases/create-a-case/save.js
- apps/manage/src/app/views/cases/create-a-case/save.test.js
- apps/manage/src/app/views/cases/index.js
- apps/manage/src/util/sharepoint.js
- packages/lib/util/name.js
- packages/sharepoint/src/sharepoint/drives/drives.js
- packages/sharepoint/src/sharepoint/drives/drives.test.js
Add item copying for SharePoint.
Add implementation for create a case
https://pins-ds.atlassian.net/browse/CROWN-63
> feat(package): sharepoint_change and implementation

- apps/manage/src/app/router.js
- packages/lib/util/name.js
> fix(crown-dev): add config to router, and update folder rename function to replaceAll

- apps/portal/src/app/views/applications/view/application-info/controller.js
- apps/portal/src/app/views/applications/view/application-info/controller.test.js
DB query error handling
https://pins-ds.atlassian.net.mcas.ms/browse/CROWN-8
> fix(crown-8): DB query error handling

- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
For all environments except dev
> chore(infrastructure): set NODE_ENV to production

- apps/manage/src/app/config.js
- infrastructure/app-manage.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/variables.tf
also disable sharepoint in test and training while there is no site setup
> chore: allow sharepoint to be disabled in any environment

- apps/manage/src/app/views/cases/view/controller.js
- apps/manage/src/app/views/cases/view/index.js
- packages/dynamic-forms/src/middleware/redirect-to-unanswered-question.js
- packages/dynamic-forms/src/middleware/redirect-to-unanswered-question.test.js
- packages/lib/util/uuid.js
- packages/lib/util/uuid.test.js
Some bug fixes on the case pages
- [fix(dynamic-forms): redirect to task list if all questions answered](https://github.com/Planning-Inspectorate/crown-developments/commit/cfb420e927fea39a3bb61990a558a0786aa2cb6a)
- [fix: ensure case ids are in a valid format to avoid a Prisma error](https://github.com/Planning-Inspectorate/crown-developments/commit/b814f0b0f8c893a777123da916c55daf6adf4370)
> Some bug fixes on the case pages

- apps/manage/src/app/views/cases/create-a-case/save.js
- apps/manage/src/app/views/cases/view/types.d.ts
- apps/manage/src/app/views/cases/view/view-model.js
- apps/manage/src/app/views/cases/view/view-model.test.js
- packages/lib/util/numbers.js
> fix(manage): map siteNorthing and siteEasting to ints for database updates

- apps/manage/src/app/views/cases/create-a-case/question-utils.js
- apps/manage/src/app/views/cases/create-a-case/questions.js
Capture agent information
https://pins-ds.atlassian.net.mcas.ms/browse/CROWN-43
https://pins-ds.atlassian.net.mcas.ms/browse/CROWN-51
https://pins-ds.atlassian.net.mcas.ms/browse/CROWN-52
https://pins-ds.atlassian.net.mcas.ms/browse/CROWN-53
https://pins-ds.atlassian.net.mcas.ms/browse/CROWN-54
https://pins-ds.atlassian.net.mcas.ms/browse/CROWN-42
> feat(manage): capture agent information

- packages/sharepoint/src/fixtures/sharepoint.js
- packages/sharepoint/src/sharepoint/drives/drives.js
- packages/sharepoint/src/sharepoint/drives/drives.test.js
> feat(packages): add sharepoint methods for adding permissions to files and folders

- .azure/pipelines/azure-pipelines-deploy.yml
> ci: verify deployments by checking git commit hash

- apps/manage/src/app/views/cases/create-a-case/save.js
- apps/manage/src/app/views/cases/create-a-case/save.test.js
- packages/lib/util/sharepoint-path.js
- applicant is granted write access to their folder in the newly created folder structure
- agent (if assigned) is granted write access to the applicant folder in the newly created folder structure 
https://pins-ds.atlassian.net/browse/CROWN-96
> feat(manage): add assign write access to applicant and agent on case create

- apps/manage/src/app/views/cases/create-a-case/questions.js
alter required validation message for application description
https://pins-ds.atlassian.net.mcas.ms/browse/CROWN-60
> feat(manage): alter required validation message for application description

- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
> chore(infrastructure): enable sharepoint in test and training

- packages/dynamic-forms/src/components/address/index.njk
add optional text to address fields
https://pins-ds.atlassian.net.mcas.ms/browse/CROWN-37
https://pins-ds.atlassian.net.mcas.ms/browse/CROWN-52
https://pins-ds.atlassian.net.mcas.ms/browse/CROWN-55
> fix(manage): add optional text to address fields

- apps/manage/src/app/views/cases/view/view-model.js
- apps/manage/src/app/views/cases/view/view-model.test.js
- packages/dynamic-forms/src/components/boolean/question.js
- packages/dynamic-forms/src/components/boolean/question.test.js
- packages/dynamic-forms/src/lib/session-answer-store.js
View Case Details: Details page
- update boolean question logic so all fields in details section render
https://pins-ds.atlassian.net/browse/CROWN-70
> feat(manage): View Case Details: Details page

- infrastructure/app-manage.tf
- infrastructure/app-portal.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/variables.tf
Align the networking settings across both apps, and add a private endpoint in all environments except dev.
> fix(infrastructure): enable private endpoint for both apps

- infrastructure/environments/dev.tfvars
Enable private endpoints in dev so that the DevOps agent can access the applications
> fix(infrastructure): enable private endpoints in dev

- apps/manage/src/app/views/cases/create-a-case/save.js
- apps/manage/src/app/views/cases/create-a-case/save.test.js
- packages/lib/util/sharepoint-path.js
Fix call to path was not returning folderId
> fix(manage): fix bug that causes permission process to not find folderId

- apps/manage/src/app/views/cases/create-a-case/journey.js
- apps/manage/src/app/views/cases/create-a-case/question-utils.js
When hasAgent is 'No' ensure correct error message displayed when applicant email is not provided
https://pins-ds.atlassian.net/browse/CROWN-38
> fix(manage): update error message if applicant email is empty

- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
> fix(infrastructure): set application ID for portal auth to deployment service principle

- packages/dynamic-forms/src/validator/coordinates-validator.js
- packages/dynamic-forms/src/validator/coordinates-validator.test.js
Address updates to ACs 3 & 4
Update error messaging for coordinates
https://pins-ds.atlassian.net/browse/CROWN-69
> fix(manage): update error messaging for coordinates

- apps/manage/src/app/views/cases/view/questions.js
Small required validation message updates.
https://pins-ds.atlassian.net/browse/CROWN-139
> fix(manage): required messages for LPA reference and Health and Safety Issues

- packages/dynamic-forms/src/lib/date-utils.js
- packages/dynamic-forms/src/validator/date-period-validator.js
- packages/dynamic-forms/src/validator/date-period-validator.test.js
Edit Case Details: Representations
update validation for date period component
https://pins-ds.atlassian.net/browse/CROWN-85
> feat(manage): update validation for date period component

- packages/database/src/seed/data-lpa-dev.js
Allow LPA address to be visible for testing
- populate LPA addresses in seed data
https://pins-ds.atlassian.net/browse/CROWN-72
> fix(manage): populate LPA addresses in seed data

- apps/manage/src/app/views/cases/view/question-utils.js
Edit Case Details:
- Hearing
- Inquiry
Update validation for hearing and inquiry sections
https://pins-ds.atlassian.net/browse/CROWN-89
https://pins-ds.atlassian.net/browse/CROWN-90
> feat(manage): update validation for hearing and inquiry sections

- apps/manage/src/app/views/cases/view/journey.js
- apps/manage/src/app/views/cases/view/question-utils.js
- apps/manage/src/app/views/cases/view/questions.js
- apps/manage/src/app/views/cases/view/view-model.js
- apps/manage/src/app/views/cases/view/view-model.test.js
- packages/dynamic-forms/src/validator/multi-field-input-validator.js
- packages/dynamic-forms/src/validator/multi-field-input-validator.test.js
Edit Case Details: Overview
allow updates to overview section of case details
Replacing PR (https://github.com/Planning-Inspectorate/crown-developments/pull/106)
https://pins-ds.atlassian.net/browse/CROWN-81
> feat(manage): Edit Case Details: Overview

- infrastructure/providers.tf
updating terraform required condition to >= 1.1.6, < 1.12.0 
latest released version 1.10.5 is within the condition range
[Ticket](https://pins-ds.atlassian.net/browse/DEV-354)
> chore(tooling): upgrading terraform version

- apps/manage/src/app/views/cases/view/view-model.js
Edit Case Details: Contacts
allow applicant and agent addresses to be edited
https://pins-ds.atlassian.net/browse/CROWN-83
> feat(manage): allow applicant and agent addresses to be edited

- apps/manage/src/app/views/cases/create-a-case/questions.js
- apps/manage/src/app/views/cases/view/questions.js
- apps/manage/src/app/views/cases/view/view-model.js
Remove Mandatory Validation on Site Hectares
https://pins-ds.atlassian.net/browse/CROWN-143
> fix(manage): remove mandatory validation for site area

- apps/manage/src/app/views/cases/create-a-case/question-utils.js
- apps/manage/src/app/views/cases/view/question-utils.js
Update validation to allow numbers in Agent/Applicant name fields
https://pins-ds.atlassian.net/browse/CROWN-142
> fix(manage): allow numbers in applicant and agent names

- apps/manage/src/app/views/cases/view/view-model.js
Address bugs raised against Edit Case Details: Overview
https://pins-ds.atlassian.net/browse/CROWN-173
> fix(manage): address bugs raised against overview section

- apps/portal/.env.example
- apps/portal/src/app/config.js
- apps/portal/src/app/router.js
- apps/portal/src/app/views/applications/index.js
- apps/portal/src/app/views/applications/view/application-info/controller.js
- apps/portal/src/app/views/applications/view/application-info/index.js
- apps/portal/src/app/views/applications/view/application-info/view.njk
- apps/portal/src/app/views/applications/view/documents/controller.js
- apps/portal/src/app/views/applications/view/documents/view.njk
- apps/portal/src/app/views/applications/view/have-your-say/controller.js
- apps/portal/src/app/views/applications/view/have-your-say/view.njk
- apps/portal/src/app/views/applications/view/index.js
- apps/portal/src/app/views/applications/view/types.d.ts
- apps/portal/src/app/views/applications/view/view-model.js
- apps/portal/src/app/views/applications/view/view-model.test.js
- apps/portal/src/util/config-middleware.js
- infrastructure/app-portal.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/variables.tf
[Portal] Application Information Page
https://pins-ds.atlassian.net/browse/CROWN-104
> feat(portal): configure application info page

- packages/database/src/migrations/20250214085903_representations_data_model/migration.sql
- packages/database/src/migrations/20250214090513_remove_redundant_is_redacted_field/migration.sql
- packages/database/src/schema.prisma
- packages/database/src/seed/data-dev.js
- packages/database/src/seed/data-static.js
- reps data model
- (seed data to be added)
https://pins-ds.atlassian.net/browse/CROWN-171
> feat(database): representations data model and static data

- .azure/pipelines/azure-pipelines-deploy.yml
> ci: update pipeline template for deploy

- apps/portal/src/app/views/applications/view/application-info/controller.js
- apps/portal/src/app/views/applications/view/application-info/view.njk
- apps/portal/src/app/views/applications/view/documents/controller.js
- apps/portal/src/app/views/applications/view/documents/view.njk
- apps/portal/src/app/views/applications/view/have-your-say/controller.js
- apps/portal/src/app/views/applications/view/have-your-say/view.njk
- apps/portal/src/app/views/applications/view/links.njk
- apps/portal/src/app/views/applications/view/types.d.ts
- apps/portal/src/app/views/applications/view/view-model.js
- removed extra container + main tags (already in main layout)
- added a links macro to manage duplicate code for displaying the list
> fix(portal): remove extra div/main, and add macro for links

- apps/manage/src/app/views/cases/view/question-utils.js
- apps/manage/src/app/views/cases/view/questions.js
BUG - Case Overview page cosmetic changes - Capitalisation
resolve cosmetic issues around casing
https://pins-ds.atlassian.net/browse/CROWN-172
> fix(manage): resolve cosmetic issues around casing

- apps/portal/src/app/views/applications/view/index.js
- apps/portal/src/app/views/applications/view/list/controller.js
- apps/portal/src/app/views/applications/view/list/controller.test.js
- apps/portal/src/app/views/applications/view/list/index.js
- apps/portal/src/app/views/applications/view/list/view.njk
- apps/portal/src/app/views/applications/view/types.d.ts
- apps/portal/src/app/views/applications/view/view-model.js
- apps/portal/src/app/views/applications/view/view-model.test.js
[Portal] Applications List Page
https://pins-ds.atlassian.net/browse/CROWN-121
> feat(portal): Applications List Page

- apps/manage/src/app/views/cases/view/questions.js
BUG - Case Overview page cosmetic changes - Capitalisation 
https://pins-ds.atlassian.net/browse/CROWN-218
> fix(manage): update text to be compliant with casing

- apps/manage/src/app/views/cases/view/view-model.js
[Fix] - Edit Case Details: Overview (Crown-81) 
- fix prisma errors occurring when trying to update a site address when the site address id is null
https://pins-ds.atlassian.net/browse/CROWN-173
> fix(manage): fix prisma issues related to site address id

- packages/lib/util/session.js
- packages/lib/util/session.test.js
Session utils for saving data to session inside a case object by ID
N/A
> feat(lib): add session data utils

- packages/dynamic-forms/src/components/boolean/question.js
Small util for boolean values - for use by manage reps
N/A
> feat(dynamic-forms): add booleanToYesNoOrNull util

- apps/manage/src/app/views/layouts/main.njk
- apps/portal/src/app/views/layouts/main.njk
- packages/lib/util/build.js
Ensure govuk javascript is included and initialised (to support manage reps work)
N/A
> fix: add govuk javascript

- packages/dynamic-forms/src/validator/validator.js
Add validator for specific questions outside of a journey - to support manage reps
N/A
> feat(dynamic-forms): add util to validate specific questions

- packages/dynamic-forms/src/components/text-entry-redact/index.njk
- packages/dynamic-forms/src/components/text-entry-redact/question.js
- packages/dynamic-forms/src/components/text-entry-redact/question.test.js
- packages/dynamic-forms/src/index.js
- packages/dynamic-forms/src/questions/questions.js
Dynamic forms component for text redaction - to support manage reps
N/A
> feat(dynamic-forms): add text-entry-redact component

- packages/database/src/seed/data-dev.js
Add email address to some of the reps contacts - to support manage reps work
N/A
> chore(database): add emails to some reps contacts

- apps/manage/src/app/views/cases/view/controller.js
- apps/manage/src/app/views/cases/view/controller.test.js
- apps/manage/src/app/views/cases/view/index.js
- apps/manage/src/app/views/cases/view/journey.js
- apps/manage/src/app/views/cases/view/publish/controller.js
- apps/manage/src/app/views/cases/view/publish/controller.test.js
- apps/manage/src/app/views/cases/view/publish/index.js
- apps/manage/src/app/views/cases/view/publish/success.njk
- apps/manage/src/app/views/cases/view/question-utils.js
- apps/manage/src/app/views/cases/view/questions.js
- apps/manage/src/app/views/cases/view/view.njk
- packages/dynamic-forms/src/lib/date-utils.js
- packages/dynamic-forms/src/lib/date-utils.test.js
- packages/lib/util/session.js
- packages/lib/util/session.test.js
**Package updates:**
- Add date utils to check if date is past, future or today with tests
- Update SessionClear to allow for arrays of fields
**Case view list updates:**
- Update cases/view view.njk to add publish and unpublish buttons based on publishDate with tests
- Add validation when clicking publish button
- Update cases/view questions to make publishDate uneditable
- Update question utils to allow for dateQuestion to process editable rows
**Publish case updates:**
- Add success page for publishing
- Add publish route
- update DB with publishDate
- display success page
https://pins-ds.atlassian.net/browse/CROWN-109
https://pins-ds.atlassian.net/browse/CROWN-91
> feat(package): add publish case functionality

- apps/manage/src/app/views/cases/view/question-utils.js
- apps/manage/src/app/views/cases/view/questions.js
- packages/lib/forms/representations/questions.js
- packages/lib/util/questions.js
To fix build
- move referenceDataToRadioOptions from manage into lib so it can used across the application
> fix(lib): move function from manage into lib

- packages/dynamic-forms/src/section.js
- packages/dynamic-forms/src/section.test.js
Expand the section condition logic to include a condition that applies to all questions in a section:
```ecma script level 4
new Section('My Section', 'my-section')
.withSectionCondition((res) => questionHasAnswer(res, questions.dependsOn, 'answer')
.addQuestion(questions.q1)
//...
```
N/A but to support the have-your-say work
> feat(dynamic-forms): add condition to apply to a whole section

- apps/portal/src/app/views/applications/view/have-your-say/journey.js
- packages/lib/forms/representations/questions.js
[Portal] Have your say: Who are you representing? (agent screen)
- add who representing and is agent adult to journey
https://pins-ds.atlassian.net/browse/CROWN-162
> feat(portal): add who representing and is agent adult to journey

- apps/manage/src/app/views/cases/view/controller.test.js
- apps/manage/src/app/views/cases/view/index.js
- apps/manage/src/app/views/cases/view/publish/controller.test.js
- apps/manage/src/app/views/cases/view/unpublish/confirm.njk
- apps/manage/src/app/views/cases/view/unpublish/controller.js
- apps/manage/src/app/views/cases/view/unpublish/controller.test.js
- apps/manage/src/app/views/cases/view/unpublish/index.js
- apps/manage/src/app/views/cases/view/unpublish/success.njk
- apps/manage/src/app/views/cases/view/view.njk
- packages/lib/testing/custom-assert.test.js
- packages/lib/testing/custom-asserts.js
- Adds a confirm unpublish page & tests
- Adds a unpublish success page & tests
- Adds custom asserts for testing 404 pages are rendered correctly.
https://pins-ds.atlassian.net/browse/CROWN-127
https://pins-ds.atlassian.net/browse/CROWN-126
> feat(manage): add unpublish case functionality

- packages/dynamic-forms/src/README.md
- packages/dynamic-forms/src/section.js
- packages/dynamic-forms/src/section.test.js
Adding a feature to dynamic forms to support multi-question conditions
N/A but to support https://pins-ds.atlassian.net/browse/CROWN-10
> feat(dynamic-forms): add multi-question conditions

- apps/portal/src/util/config-middleware.js
add link to all applications
https://pins-ds.atlassian.net/browse/CROWN-192
> feat(portal): navigation

- apps/portal/src/app/views/applications/view/have-your-say/journey.js
- packages/lib/forms/representations/question-utils.js
- packages/lib/forms/representations/questions.js
[Portal] Have your say (On behalf of an Organisation I do work for Journey)
https://pins-ds.atlassian.net/browse/CROWN-160
> feat(portal): configure on behalf of org i work for journey

- infrastructure/app-manage.tf
- infrastructure/app-portal.tf
> chore(infrastructure): update node-app-service module to 1.40 to support terraform upgrade to 1.10

- apps/portal/src/app/views/applications/view/have-your-say/journey.js
- packages/database/src/seed/data-static.js
- packages/lib/forms/representations/questions.js
[Portal] Have your say (On behalf of Org/Charity I do NOT work for)
https://pins-ds.atlassian.net/browse/CROWN-182
> feat(portal): configure journey for org/charity not work for

- apps/manage/src/app/views/cases/view/controller.test.js
- apps/manage/src/app/views/cases/view/publish/controller.test.js
- apps/portal/src/app/views/applications/index.js
- apps/portal/src/app/views/applications/list/view.njk
- apps/portal/src/app/views/applications/view/application-info/controller.js
- apps/portal/src/app/views/applications/view/application-info/controller.test.js
- apps/portal/src/app/views/applications/view/documents/controller.js
- apps/portal/src/app/views/applications/view/have-your-say/controller.js
- apps/portal/src/app/views/applications/view/have-your-say/controller.test.js
- apps/portal/src/app/views/applications/view/have-your-say/index.js
- apps/portal/src/app/views/applications/view/index.js
- apps/portal/src/app/views/applications/view/view-model.js
- apps/portal/src/app/views/applications/view/view-model.test.js
- packages/dynamic-forms/src/components/date-period/question.js
- packages/dynamic-forms/src/components/date-period/question.test.js
- packages/dynamic-forms/src/lib/date-utils.js
- packages/dynamic-forms/src/lib/date-utils.test.js
Implemented representation window check, which determine what link gets shown and if you can access a url
https://pins-ds.atlassian.net/browse/CROWN-130
https://pins-ds.atlassian.net/browse/CROWN-234
> feat(portal): implement representation window check and update application links

- apps/portal/src/app/views/applications/view/have-your-say/journey.js
- apps/portal/src/app/views/applications/view/view-model.js
> fix(portal): fixed missed urls

- apps/portal/src/app/views/layouts/main.njk
This fixes POST requests with Easy Auth enabled on non-live environments
N/A
> chore(portal): add referrer meta tag

- packages/lib/forms/representations/types.d.ts
Add type definition of the have-your-say view model
N/A to support have-your-say and manage reps work
> chore(lib): add have-your-say view-model types

- apps/portal/src/app/views/applications/view/have-your-say/journey.js
- apps/portal/src/app/views/applications/view/have-your-say/journey.test.js
- packages/lib/forms/representations/questions.js
- packages/lib/forms/representations/types.d.ts
A refactor to ensure naming is clear
N/A to support have-your-say and manage reps
> refactor: use 'myself' and 'submitter' as field prefixes for have-your-say

- apps/portal/src/app/views/applications/view/have-your-say/journey.js
- apps/portal/src/app/views/applications/view/have-your-say/journey.test.js
- apps/portal/src/app/views/layouts/forms-have-your-say-check-your-answers.njk
- packages/dynamic-forms/src/section.js
[Portal] Check your answers (Myself & On behalf of Journeys)
https://pins-ds.atlassian.net/browse/CROWN-155
https://pins-ds.atlassian.net/browse/CROWN-163
https://pins-ds.atlassian.net/browse/CROWN-161
https://pins-ds.atlassian.net/browse/CROWN-193
> feat(portal): configure have your say check your answers page

- apps/portal/src/app/views/applications/view/application-info/controller.js
- apps/portal/src/app/views/applications/view/application-info/controller.test.js
- apps/portal/src/app/views/applications/view/application-info/view.njk
Important Dates section still displaying when no dates have been added
- after fix , section only displays when dates have been set on case data
https://pins-ds.atlassian.net/browse/CROWN-283
> fix(portal): only display important dates section if values exist

- apps/manage/src/app/views/cases/view/manage-reps/index.js
- apps/manage/src/app/views/cases/view/manage-reps/view/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/view/controller.test.js
- apps/manage/src/app/views/cases/view/manage-reps/view/journey.js
- apps/manage/src/app/views/cases/view/manage-reps/view/view.njk
- packages/lib/forms/representations/questions.js
- packages/lib/forms/representations/sections.js
- packages/lib/forms/representations/sections.test.js
- packages/lib/forms/representations/types.d.ts
- packages/lib/forms/representations/view-model.js
- packages/lib/forms/representations/view-model.test.js
View representation
(working edit links to follow)
https://pins-ds.atlassian.net/browse/CROWN-164
> feat(manage): view representation page

- packages/lib/forms/representations/questions.js
- packages/lib/forms/representations/sections.js
Add "What date was the representation received?" question for view/edit reps
https://pins-ds.atlassian.net/browse/CROWN-164
> feat(manage): add reps received date

- apps/portal/src/app/views/applications/view/application-info/controller.js
- apps/portal/src/app/views/applications/view/documents/controller.js
- apps/portal/src/app/views/applications/view/have-your-say/controller.js
- apps/portal/src/app/views/applications/view/index.js
- apps/portal/src/app/views/applications/view/view-model.js
- apps/portal/src/app/views/applications/view/view-model.test.js
- apps/portal/src/app/views/applications/view/written-representations/controller.js
- apps/portal/src/app/views/applications/view/written-representations/controller.test.js
- apps/portal/src/app/views/applications/view/written-representations/index.js
- apps/portal/src/app/views/applications/view/written-representations/view.njk
- packages/dynamic-forms/src/lib/date-utils.js
- packages/dynamic-forms/src/lib/date-utils.test.js
[Portal] Written Representation Navigation visibility
https://pins-ds.atlassian.net/browse/CROWN-132
> feat(portal): Set up written reps link visibility

- apps/portal/src/app/views/layouts/forms-have-your-say-check-your-answers.njk
Update have your say cya content to reflect figma designs
https://pins-ds.atlassian.net/browse/CROWN-335
> fix(portal): Update have your say cya content to reflect figma designs

- apps/manage/src/app/views/cases/view/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/index.js
- apps/manage/src/app/views/cases/view/manage-reps/view/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/view/controller.test.js
- apps/manage/src/app/views/cases/view/manage-reps/view/journey.js
- apps/manage/src/app/views/cases/view/publish/controller.js
- apps/manage/src/app/views/cases/view/unpublish/controller.js
- apps/manage/src/app/views/cases/view/view-model.js
- packages/dynamic-forms/src/components/boolean/question.js
- packages/lib/forms/representations/types.d.ts
- packages/lib/forms/representations/view-model.js
- packages/lib/forms/representations/view-model.test.js
- packages/lib/util/database.js
- packages/lib/util/database.test.js
Edit functionality
https://pins-ds.atlassian.net/browse/CROWN-164
> feat(manage): edit representations

- packages/lib/forms/representations/questions.js
- packages/lib/forms/representations/sections.js
Add Representation Type field/question
https://pins-ds.atlassian.net/browse/CROWN-145
> feat(manage): add representation type (category) question

- apps/manage/src/app/views/cases/view/manage-reps/edit/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/edit/controller.test.js
- apps/manage/src/app/views/cases/view/manage-reps/index.js
- apps/manage/src/app/views/cases/view/manage-reps/review/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/review/controller.test.js
- apps/manage/src/app/views/cases/view/manage-reps/view/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/view/controller.test.js
- apps/manage/src/app/views/cases/view/manage-reps/view/journey.js
- apps/manage/src/app/views/cases/view/manage-reps/view/journey.test.js
- apps/manage/src/app/views/cases/view/manage-reps/view/view.njk
To be merged after #211 
https://pins-ds.atlassian.net/browse/CROWN-147
https://pins-ds.atlassian.net/browse/CROWN-179
> feat(manage): edit representations with success banner

- apps/portal/src/app/views/applications/view/have-your-say/controller.js
- apps/portal/src/app/views/applications/view/have-your-say/controller.test.js
- apps/portal/src/app/views/applications/view/have-your-say/declaration.njk
- apps/portal/src/app/views/applications/view/have-your-say/index.js
- apps/portal/src/app/views/applications/view/have-your-say/success.njk
- apps/portal/src/app/views/applications/view/types.d.ts
- packages/database/src/seed/data-dev.js
- packages/lib/forms/representations/view-model.js
- packages/lib/forms/representations/view-model.test.js
- packages/lib/util/random-reference.js
- packages/lib/util/random-reference.test.js
Adds save functionality to representation on portal
Adds declaration and success pages
https://pins-ds.atlassian.net/browse/CROWN-211
https://pins-ds.atlassian.net/browse/CROWN-156
https://pins-ds.atlassian.net/browse/CROWN-157
https://pins-ds.atlassian.net/browse/CROWN-214
> feat(portal): add declaration and success pages

- apps/manage/src/app/views/cases/view/manage-reps/view/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/view/controller.test.js
- packages/dynamic-forms/src/components/text-entry-redact/index.njk
- packages/dynamic-forms/src/components/text-entry-redact/question.js
- packages/lib/forms/representations/questions.js
- packages/lib/forms/representations/sections.js
- packages/lib/forms/representations/types.d.ts
- packages/lib/forms/representations/view-model.js
- packages/lib/forms/representations/view-model.test.js
[feat(manage): edit redacted representations](https://github.com/Planning-Inspectorate/crown-developments/commit/16a983694d06e7ab45cb32b3243b68ca010016c7)
+ a few little bug fixes:
[fix(manage): ensure edit-reps back links go to view/review](https://github.com/Planning-Inspectorate/crown-developments/commit/bdb5d4200b10aa2731de8bca2726370c3ec08794)
[fix(dynamic-forms): ensure undo-all-changes for redaction works if no history](https://github.com/Planning-Inspectorate/crown-developments/commit/a7d0caa7ebb72dab300e66fd11ca4010bddae968)
https://pins-ds.atlassian.net/browse/CROWN-363
https://pins-ds.atlassian.net/browse/CROWN-364
> feat(manage): edit redacted representations

- packages/database/src/seed/data-dev.js
- packages/dynamic-forms/src/components/text-entry-redact/question.js
- packages/lib/forms/representations/questions.js
Redaction edits were being saved to `comment` field in the database instead of `commentRedacted`
https://pins-ds.atlassian.net/browse/CROWN-363
> fix(manage): ensure redaction edits are saved to commentRedacted field

- apps/portal/src/app/views/applications/view/types.d.ts
- apps/portal/src/app/views/applications/view/view-model.js
- apps/portal/src/app/views/applications/view/view-model.test.js
- apps/portal/src/app/views/applications/view/written-representations/controller.js
- apps/portal/src/app/views/applications/view/written-representations/controller.test.js
- apps/portal/src/app/views/applications/view/written-representations/index.js
- apps/portal/src/app/views/applications/view/written-representations/pagination-options.njk
- apps/portal/src/app/views/applications/view/written-representations/pagination.njk
- apps/portal/src/app/views/applications/view/written-representations/pagination.test.js
- apps/portal/src/app/views/applications/view/written-representations/read-more/controller.js
- apps/portal/src/app/views/applications/view/written-representations/read-more/controller.test.js
- apps/portal/src/app/views/applications/view/written-representations/read-more/view.njk
- apps/portal/src/app/views/applications/view/written-representations/representation.njk
- apps/portal/src/app/views/applications/view/written-representations/view.njk
- packages/database/src/migrations/20250310152531_representations_contains_attachments/migration.sql
- packages/database/src/schema.prisma
- packages/database/src/seed/data-dev.js
- packages/lib/forms/representations/types.d.ts
[Portal] View Written Representations Page
https://pins-ds.atlassian.net/browse/CROWN-229
> feat(portal): begin configuration of written reps page

- packages/lib/forms/representations/view-model.js
- packages/lib/forms/representations/view-model.test.js
Updated to set email even when not over 18
n/a
> fix(packages): updated mapper to save email even when not over 18

- packages/lib/forms/representations/question-utils.js
- packages/lib/forms/representations/questions.js
Severity: Medium: Hint text is different from criteria
- fix hint text
- move myself and submitter is over 18 question into common util
https://pins-ds.atlassian.net/browse/CROWN-341
> fix(portal): over 18 hint text is different from criteria fix

- apps/portal/src/app/views/applications/view/documents/controller.js
- apps/portal/src/app/views/applications/view/documents/controller.test.js
- apps/portal/src/app/views/applications/view/documents/view-model.js
- apps/portal/src/app/views/applications/view/documents/view-model.test.js
https://pins-ds.atlassian.net/browse/CROWN-362
> fix(portal): don't include folders in documents list

- apps/manage/src/app/views/cases/view/manage-reps/review/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/review/controller.test.js
- apps/manage/src/app/views/cases/view/manage-reps/view/view.njk
Remove Hearing Preference from View Representation page
https://pins-ds.atlassian.net/browse/CROWN-371
> feat(manage): remove Hearing Preference from View Representation page

- apps/portal/src/app/views/applications/view/documents/controller.js
- apps/portal/src/app/views/applications/view/documents/controller.test.js
- apps/portal/src/app/views/applications/view/index.js
- apps/portal/src/app/views/applications/view/written-representations/controller.js
- apps/portal/src/app/views/applications/view/written-representations/index.js
- apps/portal/src/app/views/applications/view/written-representations/read-more/controller.js
- apps/portal/src/app/views/applications/view/written-representations/read-more/controller.test.js
- apps/portal/src/app/views/applications/view/written-representations/read-more/view.njk
- apps/portal/src/app/views/util/application-util.js
- apps/portal/src/app/views/util/documents-util.js
- apps/portal/src/app/views/util/documents-util.test.js
[Portal] Written Representations - Read More Page
- show documents if representation contains attachments
- links to docs in sharepoint
- open documents in new tabs if clicked
https://pins-ds.atlassian.net/browse/CROWN-231
https://github.com/user-attachments/assets/0aaff25e-90f1-4dd9-a2ca-a9cd597b374b
> feat(portal): Written Reps read more page

- packages/lib/forms/representations/questions.js
https://pins-ds.atlassian.net/browse/CROWN-147
https://pins-ds.atlassian.net/browse/CROWN-179
> fix(manage): use correct field name for representation type

- package-lock.json
- package.json
https://github.com/tj/connect-redis/releases/tag/v8.0.2
N/A
> build(deps): bump connect-redis from 8.0.1 to 8.0.2

- packages/lib/forms/representations/questions.js
fixed the text in the check your answers page for represented person name.
https://pins-ds.atlassian.net/browse/CROWN-401
> fix(manage): update title for represented person name

- apps/manage/src/app/views/cases/view/manage-reps/review/index.js
Missed one bit when removing wants-to-be-heard checkbox from review page
https://pins-ds.atlassian.net/browse/CROWN-371
> fix(manage): don't validate wantsToBeHeard on the review page

- apps/manage/src/app/views/cases/view/manage-reps/add/journey.test.js
- packages/dynamic-forms/src/questions/question.js
- packages/dynamic-forms/src/validator/address-validator.js
- packages/lib/forms/representations/question-utils.js
- packages/lib/forms/representations/sections.js
- packages/lib/forms/representations/sections.test.js
add on behalf of journey
https://pins-ds.atlassian.net/browse/CROWN-274
https://pins-ds.atlassian.net/browse/CROWN-277
https://pins-ds.atlassian.net/browse/CROWN-276
> feat(manage): build add-representation on behalf of journey

- apps/portal/src/app/views/applications/view/have-your-say/controller.js
- apps/portal/src/app/views/applications/view/have-your-say/success.njk
- apps/portal/src/app/views/applications/view/have-your-say/view.njk
- packages/lib/forms/custom-components/representation-comment/index.njk
Amend copy on Have your say start page
https://pins-ds.atlassian.net/browse/CROWN-393
> fix(portal): update copy for pages in have your say journey

- apps/portal/src/app/views/layouts/components/core/header.njk
Bypass Blocks - Multiple 'Skip to Main Content' CTAs Present
- remove extra govukSkipLink in header.njk
https://pins-ds.atlassian.net/browse/CROWN-385
> fix(portal): remove extra govukSkipLink in header.njk

- apps/manage/src/app/app.js
- apps/manage/src/app/config-types.d.ts
- apps/manage/src/app/config.js
- apps/manage/src/app/router.js
- apps/manage/src/app/views/cases/create-a-case/index.js
- apps/manage/src/app/views/cases/create-a-case/save.js
- apps/manage/src/app/views/cases/create-a-case/save.test.js
- apps/manage/src/app/views/cases/index.js
- apps/manage/src/app/views/layouts/forms-check-your-answers.njk
- apps/portal/src/app/config-types.d.ts
- apps/portal/src/app/config.js
- infrastructure/app-manage.tf
- infrastructure/app-portal.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/variables.tf
- packages/dynamic-forms/src/components/task-list/index.njk
- packages/dynamic-forms/src/components/task-list/task-list-multi-section.njk
- packages/dynamic-forms/src/components/task-list/task-list-single-section.njk
- packages/lib/govnotify/index.js
- packages/sharepoint/src/sharepoint/drives/drives.js
- packages/sharepoint/src/sharepoint/drives/drives.test.js
AUTOMATIC NOTIFICATION: To applicant - acknowledge pre-notification
https://pins-ds.atlassian.net/browse/CROWN-244
https://pins-ds.atlassian.net/browse/CROWN-245
> feat(manage): AUTOMATIC NOTIFICATION: To applicant - acknowledge pre-notification

- infrastructure/.terraform.lock.hcl
- infrastructure/app-manage.tf
- infrastructure/app-portal.tf
- infrastructure/app-service-plan.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/monitoring.tf
- infrastructure/variables.tf
- use multiple app instances (with per-site-scaling)
- use zone balancing
https://pins-ds.atlassian.net/browse/CROWN-220
> feat(infrastructure): setup production configuration

- apps/portal/src/app/views/applications/view/documents/view.njk
- apps/portal/src/app/views/applications/view/have-your-say/view.njk
- apps/portal/src/app/views/layouts/forms-have-your-say-check-your-answers.njk
Bypass Blocks - Heading Structure Incorrect
- fix heading structure on have your say and doc pages
https://pins-ds.atlassian.net/browse/CROWN-388
> fix(portal): fix heading structure on have your say and doc pages

- apps/manage/src/app/views/cases/view/manage-reps/add/journey.js
Back link now redirects to manage representation page when starting from representation date
https://pins-ds.atlassian.net/browse/CROWN-433
> fix(manage): fix back link to go to manage-representation page

- apps/portal/src/app/views/applications/view/types.d.ts
- apps/portal/src/app/views/applications/view/view-model.js
- apps/portal/src/app/views/applications/view/written-representations/controller.js
- apps/portal/src/app/views/applications/view/written-representations/controller.test.js
- apps/portal/src/app/views/applications/view/written-representations/read-more/controller.test.js
- apps/portal/src/app/views/applications/view/written-representations/representation.njk
Name, Role, Value - Markup to Aid Accessibility for Screen Readers
- wrap redacted comments around span for screen readers
https://pins-ds.atlassian.net/browse/CROWN-402
> fix(portal): wrap redacted comments around span for screen readers

- apps/manage/src/app/views/cases/view/index.js
- apps/manage/src/app/views/cases/view/manage-reps/add/index.js
- apps/manage/src/app/views/cases/view/manage-reps/add/journey.js
- apps/manage/src/app/views/cases/view/manage-reps/add/save.js
- apps/manage/src/app/views/cases/view/manage-reps/add/save.test.js
- apps/manage/src/app/views/cases/view/manage-reps/index.js
- apps/manage/src/app/views/layouts/forms-representation-check-your-answers.njk
- apps/portal/src/app/views/applications/view/have-your-say/controller.js
- packages/lib/forms/representations/save.js
- packages/lib/forms/representations/view-model.js
- packages/lib/forms/representations/view-model.test.js
Adds the check your answers pages to add-representation in the manage project
https://pins-ds.atlassian.net/browse/CROWN-279
https://pins-ds.atlassian.net/browse/CROWN-282
https://pins-ds.atlassian.net/browse/CROWN-280
https://pins-ds.atlassian.net/browse/CROWN-281
> feat(manage): build add-representation check your answers pages

- apps/portal/.env.example
- apps/portal/src/app/app.js
- apps/portal/src/app/config-types.d.ts
- apps/portal/src/app/config.js
- apps/portal/src/app/router.js
- apps/portal/src/app/views/layouts/components/core/header.njk
- apps/portal/src/util/config-middleware.js
- infrastructure/app-portal.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/variables.tf
Add a feature flag to set the Portal live (or not)
https://pins-ds.atlassian.net/browse/CROWN-191
> feat(portal): add 'not live' feature flag implementation

- apps/portal/src/app/config-types.d.ts
- apps/portal/src/app/router.js
- apps/portal/src/app/views/contact/controller.js
- apps/portal/src/app/views/contact/controller.test.js
- apps/portal/src/app/views/contact/index.js
- apps/portal/src/app/views/contact/view.njk
- apps/portal/src/util/config-middleware.js
Add contact page
https://pins-ds.atlassian.net/browse/CROWN-412
> feat(portal): add contact us page

- apps/portal/src/util/config-middleware.js
Add footer links
https://pins-ds.atlassian.net/browse/CROWN-505
> feat(portal): add footer links

- apps/portal/src/app/sass/components/intro-to-service-panel.scss
- apps/portal/src/app/sass/style.scss
- apps/portal/src/app/views/applications/list/controller.js
- apps/portal/src/app/views/applications/list/controller.test.js
- apps/portal/src/app/views/applications/list/view.njk
- apps/portal/src/app/views/layouts/components/core/header.njk
- apps/portal/src/app/views/layouts/components/core/intro-to-service.njk
Add intro to service to 'Application List' page
https://pins-ds.atlassian.net/browse/CROWN-411
> feat(portal): create info panel on all applications page

- apps/portal/src/app/views/applications/view/application-info/controller.js
- apps/portal/src/app/views/applications/view/application-info/controller.test.js
- apps/portal/src/app/views/applications/view/application-info/view.njk
- apps/portal/src/app/views/applications/view/have-your-say/controller.test.js
- apps/portal/src/app/views/applications/view/types.d.ts
- apps/portal/src/app/views/applications/view/view-model.js
- apps/portal/src/app/views/applications/view/view-model.test.js
Have your say CTA -reps open
https://pins-ds.atlassian.net/browse/CROWN-378
> feat(portal): add have your say section and cta to app info page

- apps/portal/src/app/views/applications/view/application-info/view.njk
Increase text size of have your say button
https://pins-ds.atlassian.net/browse/CROWN-378
> fix(portal): increase text size of have your say button

- apps/portal/src/app/views/applications/view/have-your-say/success.njk
- packages/lib/forms/custom-components/representation-comment/index.njk
Updated templates to not use hard coded email but rather the email provided by config in portal
> chore(portal):update templates to use contact email from config

- apps/portal/src/app/views/applications/view/application-info/controller.js
- apps/portal/src/app/views/applications/view/application-info/controller.test.js
- apps/portal/src/app/views/applications/view/application-info/view.njk
- apps/portal/src/app/views/applications/view/have-your-say/controller.test.js
- apps/portal/src/app/views/applications/view/view-model.js
- apps/portal/src/app/views/applications/view/view-model.test.js
Display decision section when decisionDate or decisionOutcome are populated
https://pins-ds.atlassian.net/browse/CROWN-422
> feat(portal): add decision section

- apps/portal/src/app/views/layouts/components/core/intro-to-service.njk
https://pins-ds.atlassian.net/browse/CROWN-411
> chore(portal): fix casing on intro-to-service.njk

- apps/manage/src/app/views/cases/view/journey.js
- apps/manage/src/app/views/cases/view/questions.js
- apps/manage/src/app/views/cases/view/types.d.ts
- apps/manage/src/app/views/cases/view/view-model.js
- apps/portal/src/app/views/applications/view/application-info/controller.js
- apps/portal/src/app/views/applications/view/application-info/controller.test.js
- apps/portal/src/app/views/applications/view/application-info/view.njk
- apps/portal/src/app/views/applications/view/have-your-say/controller.test.js
- apps/portal/src/app/views/applications/view/types.d.ts
- apps/portal/src/app/views/applications/view/view-model.js
- apps/portal/src/app/views/applications/view/view-model.test.js
- packages/database/src/migrations/20250326103817_application_accepted_date/migration.sql
- packages/database/src/schema.prisma
- packages/database/src/seed/data-static.js
Reword "Application Complete Date" to "Application Accepted Date"
https://pins-ds.atlassian.net/browse/CROWN-498
> feat(portal/manage): alter title from completed date to accepted date

- apps/portal/src/app/views/applications/view/application-info/controller.js
- apps/portal/src/app/views/applications/view/application-info/controller.test.js
- apps/portal/src/app/views/applications/view/application-info/view.njk
https://pins-ds.atlassian.net/browse/CROWN-422
> chore(portal): update Procedure Decision -> Application Decision

- apps/portal/src/app/sass/components/pins-table.scss
- apps/portal/src/app/sass/style.scss
- apps/portal/src/app/views/applications/list/view.njk
Fixed large applications table to avoid overflow on high zoom.
https://pins-ds.atlassian.net/browse/CROWN-390
> feat(portal): make tables stop overflowing causing 2d navigation

- packages/lib/forms/representations/view-model.js
- packages/lib/forms/representations/view-model.test.js
Put job title under submittedby contact (instead of representedContact)
https://pins-ds.atlassian.net/browse/CROWN-413
> feat(manage): fix jobtitle not showing

- apps/portal/src/app/views/static/contact/controller.js
- apps/portal/src/app/views/static/contact/controller.test.js
- apps/portal/src/app/views/static/terms-and-conditions/controller.js
- apps/portal/src/app/views/static/terms-and-conditions/controller.test.js
Fix views not found for T&C and contact pages
> fix(portal): t&c and contact page view not loading

- packages/lib/forms/representations/view-model.js
- packages/lib/forms/representations/view-model.test.js
do not need to use mapFieldValue as values are already boolean
https://pins-ds.atlassian.net/browse/CROWN-359
> fix(manage): do not need to use mapFieldValue as values are already boolean

- packages/dynamic-forms/src/validator/address-validator.js
- packages/lib/forms/representations/questions.js
update validation for postcode and person representing
https://pins-ds.atlassian.net/browse/CROWN-418
https://pins-ds.atlassian.net/browse/CROWN-445
> fix(lib): update validation for postcode and person representing

- apps/portal/src/app/service.js
> fix(portal): correct import for TokenCredentialAuthenticationProvider

- apps/manage/src/app/service.js
- apps/manage/src/app/views/cases/create-a-case/save.js
- apps/manage/src/app/views/cases/create-a-case/save.test.js
- packages/lib/govnotify/gov-notify-client.js
- packages/lib/govnotify/gov-notify-client.test.js
- packages/lib/govnotify/index.js
- packages/lib/govnotify/types.d.ts
Refactor so that the Notify client takes the template Ids and provides specific methods for each notification
N/A
> refactor(manage): add notification specific functions to notify client

- apps/manage/src/app/router.js
- apps/portal/src/app/router.js
- packages/lib/controllers/monitoring.js
- packages/lib/middleware/cache.js
https://pins-ds.atlassian.net/browse/CROWN-554
> fix: set cache-control for all pages

- apps/manage/src/app/router.js
- apps/manage/src/app/views/static/error/controller.js
- apps/manage/src/app/views/static/error/firewall-error.njk
- apps/manage/src/app/views/static/error/index.js
- apps/portal/src/app/router.js
- apps/portal/src/app/views/static/error/controller.js
- apps/portal/src/app/views/static/error/firewall-error.njk
- apps/portal/src/app/views/static/error/index.js
- infrastructure/front-door-manage.tf
- infrastructure/front-door-portal.tf
Add firewall rules and pages
https://pins-ds.atlassian.net/browse/CROWN-46
> feat(infrastructure): add firewall rules, and firewall error pages

- apps/portal/src/app/router.js
- apps/portal/src/app/views/static/accessibility-statement/controller.js
- apps/portal/src/app/views/static/accessibility-statement/controller.test.js
- apps/portal/src/app/views/static/accessibility-statement/view.njk
Add accessibility statement page
[CROWN-503-accessibility-statement-page](https://pins-ds.atlassian.net/browse/CROWN-503)
> feat(portal): add accessibility statement

- infrastructure/environments/prod.tfvars
Production notify template ID
https://pins-ds.atlassian.net/browse/CROWN-273
> chore(infrastructure): prod template id for pre_ack_template_id

- packages/database/src/seed/data-lpa-prod-read.js
To support adding a test LPA in production
https://pins-ds.atlassian.net/browse/CROWN-569
> chore(database): add test LPA id

- .azure/pipelines/azure-pipelines-db-seed.yml
> ci: fix db-seed node_script reference

- apps/manage/src/app/views/cases/view/manage-reps/view/controller.js
- apps/manage/src/app/views/cases/view/view-model.js
- apps/portal/src/app/views/static/contact/controller.test.js
- apps/portal/src/app/views/static/terms-and-conditions/controller.test.js
- packages/database/src/seed/data-dev.js
- packages/database/src/seed/data-static.js
- packages/database/src/seed/representations-data-dev.js
- packages/lib/forms/representations/sections.js
- packages/lib/forms/representations/types.d.ts
- packages/lib/forms/representations/view-model.js
- packages/lib/forms/representations/view-model.test.js
- packages/lib/util/address.js
- packages/lib/util/address.test.js
add view and edit address and contact preference to the view/review representation
https://pins-ds.atlassian.net/browse/CROWN-337
https://pins-ds.atlassian.net/browse/CROWN-338
> feat(manage): view/edit address and contact preference view rep

- packages/dynamic-forms/src/components/address/question.js
- packages/dynamic-forms/src/components/date-period/question.js
- packages/dynamic-forms/src/components/date/question.js
- packages/dynamic-forms/src/components/identifier/question.js
- packages/dynamic-forms/src/components/multi-field-input/question.js
- packages/dynamic-forms/src/components/number-entry/question.js
- packages/dynamic-forms/src/components/single-line-input/question.js
- packages/dynamic-forms/src/components/text-entry-redact/question.js
- packages/dynamic-forms/src/components/text-entry/question.js
- packages/dynamic-forms/src/components/unit-option-entry/question.js
- packages/dynamic-forms/src/questions/options-question.js
- packages/dynamic-forms/src/questions/question.js
- packages/dynamic-forms/src/questions/question.test.js
- packages/lib/forms/custom-components/representation-comment/question.js
Support static view data associated with a specific question instance
N/A - to support notification work, e.g. https://pins-ds.atlassian.net/browse/CROWN-264
> feat(dynamic-forms): add support for static view data associated with a question

- apps/portal/src/app/views/applications/view/application-info/controller.js
- apps/portal/src/app/views/applications/view/application-info/view.njk
[Portal] Application Info page: Change Representation period dates to include time
https://pins-ds.atlassian.net/browse/CROWN-377
> fix(portal): show rep period start/end date and time

- apps/portal/src/app/views/static/accessibility-statement/controller.js
- apps/portal/src/app/views/static/accessibility-statement/controller.test.js
- apps/portal/src/app/views/static/accessibility-statement/view.njk
BUG - Incorrect Accessibility Statement Header  
https://pins-ds.atlassian.net/browse/CROWN-579
> fix(portal): update accessibility statement heading

- apps/manage/src/app/config.js
- apps/manage/src/app/views/cases/view/notification.js
- apps/manage/src/app/views/cases/view/notification.test.js
- apps/manage/src/app/views/cases/view/questions.js
- apps/manage/src/app/views/cases/view/types.d.ts
- apps/manage/src/app/views/cases/view/update-case.js
- apps/manage/src/app/views/cases/view/update-case.test.js
- apps/manage/src/app/views/cases/view/view-model.js
- infrastructure/app-manage.tf
- infrastructure/app-portal.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/variables.tf
- packages/database/src/migrations/20250408121434_not_nationally_important_email_flag/migration.sql
- packages/database/src/schema.prisma
- packages/lib/govnotify/gov-notify-client.js
- packages/lib/govnotify/gov-notify-client.test.js
- packages/lib/govnotify/types.d.ts
AUTOMATIC NOTIFICATION: To applicant - application not of national importance
Amend copy on 'Turned away date' page
https://pins-ds.atlassian.net/browse/CROWN-459
https://pins-ds.atlassian.net/browse/CROWN-454
> feat(manage): application not of national importance notification

- apps/manage/src/app/views/cases/view/update-case.js
- apps/manage/src/app/views/cases/view/update-case.test.js
Issue raised during testing around URLs not linking to pages.
- add links to pages for errors if thrown on date received
https://pins-ds.atlassian.net/browse/CROWN-621
Fix for: https://pins-ds.atlassian.net/browse/CROWN-252
> fix(manage): add links to pages for errors if thrown on date received

- packages/lib/forms/representations/questions.js
- packages/lib/forms/representations/sections.js
- packages/lib/forms/representations/view-model.js
- packages/lib/forms/representations/view-model.test.js
- packages/sharepoint/src/sharepoint/drives/drives.test.js
Fixed issue where wantsToBeHeard was appearing twice in the view/review representation and one was uneditable
https://pins-ds.atlassian.net/browse/CROWN-620
> fix(packages): remove duplicate wantsToBeHeard from section and align questions

- packages/lib/govnotify/gov-notify-client.js
Add a log to view message errors from notify
> fix(package): add log for message error from notify

- apps/portal/src/app/views/applications/view/have-your-say/save.js
- apps/portal/src/app/views/applications/view/have-your-say/save.test.js
- apps/portal/src/app/views/applications/view/types.d.ts
Add coordinates to be site address if no siteAddress for emails.
https://pins-ds.atlassian.net/browse/CROWN-638
> fix(portal): fix email not sending due to address

- apps/portal/src/app/views/applications/view/have-your-say/journey.test.js
- apps/portal/src/app/views/applications/view/have-your-say/save.js
- apps/portal/src/app/views/applications/view/have-your-say/save.test.js
- apps/portal/src/app/views/applications/view/view-model.js
- apps/portal/src/app/views/applications/view/view-model.test.js
- apps/portal/src/app/views/applications/view/written-representations/controller.js
- apps/portal/src/app/views/applications/view/written-representations/controller.test.js
- apps/portal/src/app/views/applications/view/written-representations/read-more/controller.js
- apps/portal/src/app/views/applications/view/written-representations/read-more/controller.test.js
- packages/database/src/migrations/20250417112658_remove_is_adult/migration.sql
- packages/database/src/schema.prisma
- packages/lib/forms/representations/question-utils.js
- packages/lib/forms/representations/questions.js
- packages/lib/forms/representations/sections.js
- packages/lib/forms/representations/sections.test.js
- packages/lib/forms/representations/types.d.ts
- packages/lib/forms/representations/view-model.js
- packages/lib/forms/representations/view-model.test.js
remove isAdult question, data, and logic 
https://pins-ds.atlassian.net/browse/CROWN-637
> fix(package): remove isAdult question

- .azure/pipelines/azure-pipeline-purge-container-registry.yml
New pipeline to clean up Docker images that aren't in use
https://pins-ds.atlassian.net/browse/DEV-325
> ci: add azure-pipeline-purge-container-registry.yml

- .azure/pipelines/azure-pipeline-purge-container-registry.yml
Following #329 updating the version to fix a bug
> ci: update purge container registry pipeline to 3.21.1

- apps/portal/src/app/app.js
- apps/portal/src/app/config-types.d.ts
- apps/portal/src/app/config.js
- apps/portal/src/app/service.js
- apps/portal/src/app/views/layouts/main.njk
- apps/portal/src/util/config-middleware.js
- apps/portal/src/util/csp-middleware.js
- infrastructure/app-portal.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/variables.tf
https://pins-ds.atlassian.net/browse/CROWN-636
> feat: add google analytics tags to the Portal app

- apps/portal/src/app/app.js
- apps/portal/src/app/views/layouts/components/core/cookie-banner.njk
- apps/portal/src/app/views/layouts/main.njk
- apps/portal/src/app/views/static/cookies/controller.js
- apps/portal/src/app/views/static/cookies/view.njk
- apps/portal/src/util/cookies.js
- apps/portal/src/util/cookies.test.js
Add a cookie banner and logic for setting an analytics cookie preference
https://pins-ds.atlassian.net/browse/CROWN-708
> feat(portal): add cookie banner

- apps/portal/src/app/app.js
- apps/portal/src/app/config-types.d.ts
- apps/portal/src/app/config.js
- apps/portal/src/app/service.js
- apps/portal/src/app/views/layouts/main.njk
- apps/portal/src/app/views/static/cookies/controller.js
- apps/portal/src/app/views/static/cookies/controller.test.js
- apps/portal/src/util/config-middleware.js
- apps/portal/src/util/cookies.js
- apps/portal/src/util/cookies.test.js
- apps/portal/src/util/csp-middleware.js
- infrastructure/app-portal.tf
Don't use the default Google cookie settings which uses the root domain. This conflicts with the NSIP site.
https://pins-ds.atlassian.net/browse/CROWN-636
> fix(portal): set cookie domain

- apps/manage/src/app/views/cases/view/manage-reps/list/view.njk
Update 'Interested Party' Field Name to 'From' on Manage Representations Page
https://pins-ds.atlassian.net/browse/CROWN-604
> fix(manage): update heading on manage reps from interested party to from

- apps/portal/src/app/views/static/cookies/view.njk
Simple copy changes to align
https://pins-ds.atlassian.net/browse/CROWN-717
> chore(portal): fix cookie page content to match document

- apps/portal/src/app/views/layouts/components/core/banner.njk
- apps/portal/src/util/config-middleware.js
> fix(portal): add feedback form to phase banner

- apps/portal/src/app/views/applications/view/have-your-say/index.js
- apps/portal/src/app/views/applications/view/have-your-say/journey.js
- apps/portal/src/app/views/applications/view/have-your-say/journey.test.js
- packages/lib/forms/representations/question-utils.js
- packages/lib/forms/representations/sections.js
- packages/lib/forms/representations/sections.test.js
[Portal] Add 'Do you want to include attachments with your comment?' page to Have your Say journey
https://pins-ds.atlassian.net/browse/CROWN-646
https://pins-ds.atlassian.net/browse/CROWN-723
https://pins-ds.atlassian.net/browse/CROWN-724
https://pins-ds.atlassian.net/browse/CROWN-725
> feat(portal): add has attachments screen to have your say journey

- apps/manage/src/app/views/cases/view/manage-reps/add/journey.js
- apps/manage/src/app/views/cases/view/manage-reps/manage-reps-utils.js
- apps/manage/src/app/views/cases/view/manage-reps/review/journey.js
- apps/manage/src/app/views/cases/view/manage-reps/view/journey.js
- apps/manage/src/app/views/cases/view/manage-reps/view/view.njk
- apps/manage/src/app/views/cases/view/unpublish/confirm.njk
- apps/manage/src/app/views/cases/view/view.njk
- apps/manage/src/app/views/layouts/forms-check-your-answers.njk
- apps/manage/src/app/views/layouts/forms-question.njk
- apps/manage/src/app/views/layouts/forms-representation-check-your-answers.njk
- apps/manage/src/app/views/layouts/main.njk
Update the tab titles for the Manage application
https://pins-ds.atlassian.net/browse/CROWN-446
> feat(manage): update tab titles

- apps/manage/src/app/views/cases/view/manage-reps/review/index.js
- apps/manage/src/app/views/cases/view/manage-reps/validation-middleware.js
- apps/manage/src/app/views/cases/view/manage-reps/validation-middleware.test.js
- apps/manage/src/app/views/cases/view/manage-reps/view/controller.js
- packages/database/src/seed/data-static.js
- packages/lib/forms/representations/questions.js
Add validation to manage representation
https://pins-ds.atlassian.net/browse/CROWN-417
> feat(manage): add validation before reviewing representation

- apps/manage/src/app/views/cases/view/manage-reps/add/index.js
- apps/manage/src/app/views/cases/view/manage-reps/add/journey.js
- packages/lib/forms/representations/sections.js
- packages/lib/forms/representations/sections.test.js
[Manage] Add 'Do you want to include attachments with your comment?' page - Add Representation journey
https://pins-ds.atlassian.net/browse/CROWN-664
https://pins-ds.atlassian.net/browse/CROWN-684
https://pins-ds.atlassian.net/browse/CROWN-691
https://pins-ds.atlassian.net/browse/CROWN-692
> feat(manage): add attachments question to add reps journey

- apps/manage/src/app/views/cases/view/question-utils.js
update errors for organisation name in edit case
https://pins-ds.atlassian.net/browse/CROWN-806
> fix(manage): update errors for organisation name in edit case

- apps/manage/src/app/views/cases/list/view.njk
Fixes tab title in Manage app
https://pins-ds.atlassian.net/browse/CROWN-781
> fix(manage): fixes tab title for all cases page

- packages/dynamic-forms/src/validator/document-upload-validator.js
- packages/dynamic-forms/src/validator/document-upload-validator.test.js
- packages/lib/forms/custom-components/representation-attachments/index.njk
- packages/lib/forms/custom-components/representation-attachments/question.js
- packages/lib/forms/custom-components/representation-attachments/question.test.js
> fix(lib): encode and decode form so that raw json is not in for value

- apps/manage/package.json
- apps/manage/src/app/service.js
- apps/manage/src/app/views/cases/view/manage-reps/add/index.js
- apps/manage/src/app/views/layouts/main.njk
- package-lock.json
[Manage] Add 'Select Attachments' page - Add Reps journey
https://pins-ds.atlassian.net/browse/CROWN-665
https://pins-ds.atlassian.net/browse/CROWN-681
https://pins-ds.atlassian.net/browse/CROWN-682
https://pins-ds.atlassian.net/browse/CROWN-683
https://pins-ds.atlassian.net/browse/CROWN-666
> feat(manage): implement doc upload for back office manage app

- apps/manage/package.json
- apps/manage/src/app/service.js
- apps/manage/src/app/views/cases/view/manage-reps/add/index.js
- apps/manage/src/app/views/layouts/main.njk
- package-lock.json
Reverts Planning-Inspectorate/crown-developments#378
> Revert "feat(manage): implement doc upload for back office manage app"

- apps/portal/src/app/router.js
- apps/portal/src/app/sass/components/pins-chevron-cards.scss
- apps/portal/src/app/sass/style.scss
- apps/portal/src/app/views/static/detailed-information/controller.js
- apps/portal/src/app/views/static/detailed-information/controller.test.js
- apps/portal/src/app/views/static/detailed-information/view.njk
- apps/portal/src/util/config-middleware.js
- packages/lib/views/chevron-card/chevron-card.njk
Implement 'Detailed Information' Page
Implemented a detailed information page which includes chevrons for each link. A tab has also been added next to 'all applications' so a user can access throughout.
777 https://pins-ds.atlassian.net/browse/CROWN-777
> feat(portal): implement detailed information page

- apps/portal/src/app/views/applications/view/have-your-say/declaration.njk
- apps/portal/src/app/views/applications/view/have-your-say/save.js
- apps/portal/src/app/views/applications/view/have-your-say/save.test.js
- apps/portal/src/app/views/static/terms-and-conditions/controller.test.js
- packages/lib/forms/custom-components/representation-attachments/upload-documents.js
- packages/lib/forms/representations/save.js
- packages/lib/util/handle-attachments.js
- packages/lib/util/handle-attachments.test.js
- packages/lib/util/questions.js
- packages/lib/util/sharepoint-path.js
- packages/lib/util/sharepoint-path.test.js
- packages/sharepoint/src/sharepoint/drives/drives.js
- packages/sharepoint/src/sharepoint/drives/drives.test.js
Add representation attachments handling on submission
https://pins-ds.atlassian.net/browse/CROWN-652
https://pins-ds.atlassian.net/browse/CROWN-735
https://pins-ds.atlassian.net/browse/CROWN-736
https://pins-ds.atlassian.net/browse/CROWN-737
> feat(portal): update database and move files on submission of representation attachments

- apps/portal/src/app/views/static/accessibility-statement/view.njk
Update content of accessibility statement in line with v7 (02/06/25)
https://pins-ds.atlassian.net/browse/CROWN-833
> fix(portal): update accessibility statement 04-06-25

- apps/portal/src/app/views/applications/view/have-your-say/view.njk
"how we use your data" Detail added to the "have your say" page 
https://pins-ds.atlassian.net/jira/software/projects/CROWN/boards/267?selectedIssue=CROWN-655
> feat(portal): how we process your data added onto have your say

- apps/portal/src/app/views/layouts/components/core/header.njk
Link added to the planning inspectorate logo to the PINS homepage
https://pins-ds.atlassian.net/jira/software/projects/CROWN/boards/267?selectedIssue=CROWN-705
> feat(portal): link added to planning inspectorate logo in header

- apps/portal/src/app/views/static/accessibility-statement/view.njk
Fixed typo on accessibility statement page
https://pins-ds.atlassian.net/browse/CROWN-893
> fix(portal): fix accessibility statement typo

- packages/lib/forms/custom-components/representation-attachments/question.js
- packages/lib/forms/representations/save.js
Move session clearing to component
https://pins-ds.atlassian.net/browse/CROWN-872
> feat(package-lib): move session clearing to the component

- apps/manage/src/app/views/layouts/forms-representation-check-your-answers.njk
Change CYA CTA from Accept and continue to Accept and submit
https://pins-ds.atlassian.net/browse/CROWN-894
> fix(manage): update CYA CTA to Accept and submit

- apps/manage/src/app/views/cases/view/manage-reps/add/save.js
- apps/manage/src/app/views/cases/view/manage-reps/add/save.test.js
- apps/portal/src/app/views/applications/view/have-your-say/save.test.js
- packages/lib/forms/custom-components/representation-attachments/question.js
- packages/lib/forms/representations/save.js
Files now move correctly when using the on-behalf-of journey, as a result it no longer continues to add files to the session folder
https://pins-ds.atlassian.net/browse/CROWN-889
> fix(package): fix documents not moving when using on-behalf-of path

- apps/manage/src/app/views/cases/view/question-utils.js
Update remove inquiry and hearing dates button colour from warning to secondary
https://pins-ds.atlassian.net/browse/CROWN-501
> feat(manage): update remove dates button colour to secondary

- apps/portal/src/app/views/applications/view/types.d.ts
- apps/portal/src/app/views/applications/view/view-model.js
- apps/portal/src/app/views/applications/view/view-model.test.js
- apps/portal/src/app/views/applications/view/written-representations/controller.js
- apps/portal/src/app/views/applications/view/written-representations/controller.test.js
- apps/portal/src/app/views/applications/view/written-representations/read-more/controller.js
- apps/portal/src/app/views/applications/view/written-representations/read-more/controller.test.js
- apps/portal/src/app/views/applications/view/written-representations/read-more/view.njk
- apps/portal/src/app/views/applications/view/written-representations/representation.njk
- packages/lib/documents/get.js
- packages/lib/documents/get.test.js
- packages/lib/util/handle-attachments.js
- packages/lib/util/random-reference.js
- packages/lib/util/random-reference.test.js
- packages/lib/util/sharepoint-path.js
- packages/lib/util/sharepoint-path.test.js
Add document viewing to front office for new file-upload feature
https://pins-ds.atlassian.net/browse/CROWN-698
> Crown 698 technical amend method on how representation attachments are displayed on the fo

- apps/manage/src/app/views/cases/view/manage-reps/review/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/review/controller.test.js
- apps/manage/src/app/views/cases/view/manage-reps/review/index.js
- apps/manage/src/app/views/cases/view/manage-reps/review/redact-document.njk
prevent errors on document view during review journey
https://pins-ds.atlassian.net/browse/CROWN-675
https://pins-ds.atlassian.net/browse/CROWN-942
> fix(manage): prevent errors on document view during review journey

- apps/manage/src/app/views/cases/view/manage-reps/review/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/review/controller.test.js
- apps/manage/src/app/views/cases/view/manage-reps/review/redact-document.njk
- apps/manage/src/app/views/cases/view/manage-reps/validation-middleware.test.js
Add hint text to 'Redact Original Document' page for when you are replacing the redacted document
https://pins-ds.atlassian.net/browse/CROWN-954
> feat(manage): Add hint text to 'Redact Original Document' page for when you are replacing the redacted document

- packages/lib/forms/custom-components/representation-attachments/question.js
- packages/lib/forms/representations/save.js
Revert session clearing location to fix a bug temporarily while file upload code is in flight
> fix(package): reverting session clear moved

- .husky/pre-commit
> chore: remove redundant "run format" on pre-commit, covered by lint-staged

- apps/portal/src/app/views/applications/view/have-your-say/declaration.njk
Severity: Minor - declaration page uses inconsistent font size and weight
https://pins-ds.atlassian.net/browse/CROWN-959
> fix(portal): ensure declaration page submit button has correct font size

- package-lock.json
update form-data on-header, eslint, and brace-expansion to address vulnerabilities
> chore(packages): update form-data on-header eslint and brace-expansion to address vulnerabilities

- apps/manage/src/app/views/cases/view/questions.js
- package-lock.json
- package.json
Override emptyErrorMessage for date on site visit field
https://pins-ds.atlassian.net/browse/CROWN-455
> fix(manage): override emptyErrorMessage for date on site visit field

- package-lock.json
- package.json
- packages/lib/forms/custom-components/representation-attachments/document-validation-util.js
Update file-type to v21.0, required change in importing. All file upload validation works as expected.
> chore(packages): update file-type version to 21.0

- package-lock.json
- package.json
> fix(manage): update dynamic-forms to fix redaction UI

- apps/manage/src/app/views/cases/view/manage-reps/edit/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/edit/save.js
- apps/manage/src/app/views/cases/view/manage-reps/edit/save.test.js
- apps/manage/src/app/views/cases/view/manage-reps/index.js
- apps/manage/src/app/views/cases/view/manage-reps/view/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/withdraw/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/withdraw/controller.test.js
- apps/manage/src/app/views/cases/view/manage-reps/withdraw/questions.js
- packages/lib/forms/custom-components/representation-attachments/question.js
- packages/lib/forms/custom-components/representation-attachments/question.test.js
- packages/lib/forms/custom-components/representation-attachments/upload-documents.js
- packages/lib/forms/custom-components/representation-attachments/upload-documents.test.js
- packages/lib/forms/representations/questions.js
- packages/lib/forms/representations/sections.js
- packages/lib/forms/representations/sections.test.js
- packages/lib/forms/representations/view-model.js
- packages/lib/forms/representations/view-model.test.js
[Manage] View Representation page - Withdrawn reps conditional fields
[Manage] Edit Withdrawn Reps
https://pins-ds.atlassian.net/browse/CROWN-597
https://pins-ds.atlassian.net/browse/CROWN-598
> feat(manage): view and edit withdrawal fields on Representation page

- packages/database/src/seed/data-lpa-prod-read.js
Seed was failing to get emails due to a whitespace. It should now trim correctly.
https://pins-ds.atlassian.net/browse/CROWN-1046
> fix(database): data-lpa-prod-read imports emails correctly

- apps/manage/src/app/views/cases/view/manage-reps/withdraw/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/withdraw/controller.test.js
- apps/manage/src/app/views/cases/view/manage-reps/withdraw/journey.js
Severity: VERY LOW: Withdrawn rep navigating to the wrong page when completed
Severity; LOW: Withdrawn reps back button navigation is incorrect
https://pins-ds.atlassian.net/browse/CROWN-1064
https://pins-ds.atlassian.net/browse/CROWN-1074
> fix(manage): fix routing on withdrawal of reps success and initial back link

- packages/lib/forms/representations/questions.js
Severity low: Select Withdrawal reason error message is incorrect
https://pins-ds.atlassian.net/browse/CROWN-1076
> fix(manage): update error message for withdrawal reason field

- apps/manage/src/app/views/cases/view/questions.js
- package-lock.json
- package.json
[Manage] Allow users to remove Procedure 
https://pins-ds.atlassian.net/browse/CROWN-499
> feat(manage): allow users to remove their procedure choice

- apps/manage/src/app/app.js
- apps/manage/src/app/sass/style.scss
- apps/manage/src/app/views/cases/list/controller.js
- apps/manage/src/app/views/cases/list/controller.test.js
- apps/manage/src/app/views/cases/list/view.njk
- packages/lib/middleware/query-middleware.js
- packages/lib/middleware/query-middleware.test.js
- packages/lib/util/search-queries.js
- packages/lib/util/search-queries.test.js
- packages/lib/views/search-bar/search-bar.njk
Add search bar and search by case reference functionality to Manage applications list
Add clear search link if no cases are found
Update the look of create case to fit
Update table to MoJ sortable table on Manage applications list
https://pins-ds.atlassian.net/browse/CROWN-208
https://pins-ds.atlassian.net/browse/CROWN-935
> feat(manage): add search by case reference to applications list

- packages/lib/views/search-bar/search-bar.njk
Allow label and hint to be hidden
Pre-emptive work to unblock other search tickets
> feat(package): add hidden to label and hint to hide them

- apps/portal/src/app/views/applications/view/view-model.js
- apps/portal/src/app/views/applications/view/written-representations/controller.js
- apps/portal/src/app/views/applications/view/written-representations/controller.test.js
- apps/portal/src/app/views/applications/view/written-representations/representation.njk
- package-lock.json
- package.json
- packages/lib/forms/custom-components/representation-comment/question.js
- packages/lib/forms/custom-components/representation-comment/question.test.js
- packages/lib/forms/representations/question-utils.js
- packages/lib/util/questions.js
- packages/lib/util/questions.test.js
Truncate Representation Summary on Check Answers pages
https://pins-ds.atlassian.net/browse/CROWN-239
> feat(apps): truncate any representation comments that exceed 500 chars

- apps/manage/src/app/views/cases/list/view.njk
Severity: LOW: Ordering cases by reference returns an incorrect order
https://pins-ds.atlassian.net/browse/CROWN-1094
> fix(manage): resolve the sort value used for reference column

- apps/manage/src/app/sass/style.scss
- apps/manage/src/app/views/cases/view/manage-reps/list/controller.js
- apps/manage/src/app/views/cases/view/manage-reps/list/controller.test.js
- apps/manage/src/app/views/cases/view/manage-reps/list/view.njk
- packages/lib/views/pagination/pagination-options.njk
[Manage] - Manage Representations Pagination
https://pins-ds.atlassian.net/browse/CROWN-832
> feat(manage): add pagination links to back office manage reps

- package-lock.json
- package.json
> chore(deps): migrate to express 5.1.0

- infrastructure/front-door-manage.tf
- infrastructure/front-door-portal.tf
Prod Issue: Firewall triggered
https://pins-ds.atlassian.net/browse/CROWN-1181
> chore(infra): update exclusions to include MS-ThreatIntel-SQLI rule 99031003

- apps/manage/src/.static/index.css
- apps/manage/src/app/views/cases/view/application-updates/view.njk
- apps/portal/src/app/sass/style.scss
- apps/portal/src/app/views/applications/view/application-info/controller.js
- apps/portal/src/app/views/applications/view/application-info/controller.test.js
- apps/portal/src/app/views/applications/view/application-info/view.njk
- apps/portal/src/app/views/applications/view/application-updates/controller.js
- apps/portal/src/app/views/applications/view/application-updates/controller.test.js
- apps/portal/src/app/views/applications/view/application-updates/view.njk
- apps/portal/src/app/views/applications/view/documents/controller.js
- apps/portal/src/app/views/applications/view/documents/controller.test.js
- apps/portal/src/app/views/applications/view/have-your-say/controller.js
- apps/portal/src/app/views/applications/view/have-your-say/controller.test.js
- apps/portal/src/app/views/applications/view/index.js
- apps/portal/src/app/views/applications/view/types.d.ts
- apps/portal/src/app/views/applications/view/view-model.js
- apps/portal/src/app/views/applications/view/view-model.test.js
- apps/portal/src/app/views/applications/view/written-representations/controller.js
- apps/portal/src/app/views/applications/view/written-representations/controller.test.js
- apps/portal/src/app/views/applications/view/written-representations/read-more/controller.js
- apps/portal/src/app/views/applications/view/written-representations/read-more/controller.test.js
- apps/portal/src/app/views/util/application-util.js
- apps/portal/src/app/views/util/application-util.test.js
- apps/portal/src/app/views/util/documents-util.test.js
Application updates page
Latest update on 'Application information' page
Add 'Application updates' to side navigation in front office
https://pins-ds.atlassian.net/browse/CROWN-1051
https://pins-ds.atlassian.net/browse/CROWN-1052
https://pins-ds.atlassian.net/browse/CROWN-1053
> feat(portal): add application updates page to portal

- packages/database/src/seed/data-static.js
Application stages display text updated: 
- "Written Representation" is now "Written representation"
- "Decision" is now "Reporting and decision"
https://pins-ds.atlassian.net/browse/CROWN-1146
> fix(database): update display names for Decision and Written Representation application stages

- apps/manage/src/app/app.js
- apps/manage/src/app/sass/style.scss
- apps/manage/src/app/views/layouts/main.njk
- apps/portal/src/app/app.js
- apps/portal/src/app/sass/style.scss
- apps/portal/src/app/views/layouts/main.njk
- packages/lib/forms/custom-components/representation-attachments/index.njk
- packages/lib/util/build.js
Adds a dynamic banner that displays when a file is being uploaded
https://pins-ds.atlassian.net/browse/CROWN-1185
> feat(package): add a banner to upload files pages to inform users an upload is in progress

- apps/portal/src/app/views/applications/view/have-your-say/view.njk
Updating the content on the "Have your say" section in portal
1013 https://pins-ds.atlassian.net/browse/CROWN-1013
> fix(portal): update content on have your say section

- apps/manage/src/app/views/cases/view/journey.js
- apps/manage/src/app/views/cases/view/journey.test.js
- apps/manage/src/app/views/cases/view/types.d.ts
- apps/manage/src/app/views/cases/view/view-model.js
- apps/manage/src/app/views/cases/view/view-model.test.js
case management conference date is no longer needed for hearing but to be kept for inquiry.
322 https://pins-ds.atlassian.net/browse/CROWN-322
> fix(manage): remove case management conference date from hearing questions

- apps/manage/src/app/views/cases/view/journey.js
- apps/manage/src/app/views/cases/view/journey.test.js
- apps/manage/src/app/views/cases/view/types.d.ts
- apps/manage/src/app/views/cases/view/view-model.test.js
statement date is no longer needed for hearing but to be kept for inquiry.
937 https://pins-ds.atlassian.net/browse/CROWN-937
> fix(manage): remove statement date from hearing questions
